
FROM python:3.10-slim

# Evitar archivos .pyc y buffering
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Instalar dependencias del sistema necesarias
RUN apt-get update && apt-get install -y --no-install-recommends     build-essential     && rm -rf /var/lib/apt/lists/*

# Instalar librerías pesadas de Ciencia de Datos
RUN pip install --no-cache-dir pandas numpy matplotlib requests beautifulsoup4 pypdf

WORKDIR /app
